name: demangler CI
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc-version: [ "ghc96", "ghc94", "ghc92", "ghc810", "ghc88" ]
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-23.05
      - uses: cachix/cachix-action@v12
        with:
          name: galois
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: build ${{ matrix.ghc-version }}
        shell: bash
        run: nix build -L .#demangler.${{ matrix.ghc-version }}
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-23.05
      - uses: cachix/cachix-action@v12
        with:
          name: galois
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: test
        shell: bash
        run: nix build .#TESTS
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-23.05
      - uses: cachix/cachix-action@v12
        with:
          name: galois
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: doc
        shell: bash
        run: nix build .#DOC
